CONTAINER_NAME=patients_api

up:
	docker-compose up

down:
	docker-compose down

.PHONY:test
test:
	make up
	docker exec -it $(CONTAINER_NAME) npm run test

.PHONY:coverage
coverage:
	make up
	docker exec -it $(CONTAINER_NAME) npm run test:cov

logs:
	docker-compose logs --follow

bash:
	make up
	docker exec -it $(CONTAINER_NAME) bash

build:
	docker-compose build